# vim:set ft=tmux:

# --> Catppuccin (Ashes)
set -ogq @thm_bg "#1c2023"
set -ogq @thm_fg "#c7ccd1"

# Colors
set -ogq @thm_rosewater "#c7c795"
set -ogq @thm_flamingo "#c79595"
set -ogq @thm_rosewater "#d0d09e"
set -ogq @thm_pink "#c795ae"
set -ogq @thm_mauve "#ae95c7"
set -ogq @thm_red "#c79595"
set -ogq @thm_maroon "#d09eb7"
set -ogq @thm_peach "#c7ae95"
set -ogq @thm_yellow "#c7c795"
set -ogq @thm_green "#aec795"
set -ogq @thm_teal "#8fb4b5"
set -ogq @thm_sky "#9eb7d0"
set -ogq @thm_sapphire "#8ca5be"
set -ogq @thm_blue "#95aec7"
set -ogq @thm_lavender "#a58cbe"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#44484b"
set -ogq @thm_subtext_0 "#1c2023"
set -ogq @thm_overlay_2 "#3a3e41"
set -ogq @thm_overlay_1 "#303437"
set -ogq @thm_overlay_0 "#303437"
set -ogq @thm_surface_2 "#3a3e41"
set -ogq @thm_surface_1 "#303437"
set -ogq @thm_surface_0 "#272b2e"
set -ogq @thm_mantle "#24282b"
set -ogq @thm_crust "#161a1d"
